[package]
  cjc-version = "1.0.0"
  name = "weakcj"
  description = "nothing here"
  version = "0.1.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
